#!/bin/bash
#
# Copyright 2002 Ben Escoto <ben@emerose.org>
# Copyright 2007 Kenneth Loafman <kenneth@loafman.com>
# Copyright 2011 Canonical Ltd
#
# This file is part of duplicity.
#
# Duplicity is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# Duplicity is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with duplicity; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# Go to directory housing this script
cd `dirname $0`

# run against all supported python versions
for v in 2.4 2.5 2.6 2.7; do
    if [ ! -e /usr/bin/python$v ]; then
        echo "python$v not found on system"
        continue
    fi

    echo "========== Compiling librsync for python$v =========="
    pushd ../duplicity
    python$v ./compilec.py
    popd

    for t in `ls auto/*.py`; do
        if [ "$t" = "auto/helper.py" ]; then
            continue
        fi
        echo "========== Running $t for python$v =========="
        pushd .
        if ! env PYTHONPATH=.. python$v -u $t -v 2>&1; then
          echo "Test failed"
          exit 1
        fi
        popd
        echo "========== Finished $t for python$v =========="
        echo
        echo
    done
done
